-------------------------------------------------------------
/* SPRING 계정 접속 후 테이블, 시퀀스 생성 */

/* 강의실(CLASS) 테이블 생성*/
CREATE TABLE "CLASS"(
	"CLASS_NO"      NUMBER,
	"TRINNER_NO"    NUMBER,
	"THUMBNAIL_IMG" VARCHAR2(300),
	"CLASS_CODE"		NUMBER,
	
	CONSTRAINT "CLASS_PK"         PRIMARY KEY("CLASS_NO")
);


COMMENT ON COLUMN "CLASS"."CLASS_NO"       IS '강의실 번호(PK)';
COMMENT ON COLUMN "CLASS"."TRINNER_NO"     IS '강사 번호';
COMMENT ON COLUMN "CLASS"."THUMBNAIL_IMG"  IS '썸네일';
COMMENT ON COLUMN "CLASS"."CLASS_CODE"     IS '강의번호';

CREATE TABLE "TRAINNER_CLASS"(
	"CLASS_CODE"		NUMBER,
	"CLASS_TITLE"		VARCHAR2(300),
	"CLASS_DETAIL"	VARCHAR2(300),
	"CLASS_HITS"		NUMBER,
	"UPLOAD_DATE"	DATE DEFAULT CURRENT_DATE,
	"BILLING_DATE"	DATE DEFAULT CURRENT_DATE,
	
	CONSTRAINT "TRAINNER_CLASS_PK" PRIMARY KEY("CLASS_CODE")
);


COMMENT ON COLUMN "TRAINNER_CLASS"."CLASS_CODE"    IS '강의번호(PK)';
COMMENT ON COLUMN "TRAINNER_CLASS"."CLASS_TITLE"   IS '강의제목';
COMMENT ON COLUMN "TRAINNER_CLASS"."CLASS_DETAIL"  IS '강의내용';
COMMENT ON COLUMN "TRAINNER_CLASS"."CLASS_HITS"    IS '조회수';
COMMENT ON COLUMN "TRAINNER_CLASS"."UPLOAD_DATE"   IS '게시일';
COMMENT ON COLUMN "TRAINNER_CLASS"."BILLING_DATE"  IS '수정일';

/* 회원(MEMBER) 테이블 생성*/
CREATE TABLE "MEMBER"(
	"MEMBER_NO"       NUMBER,
	"MEMBER_EMAIL"    VARCHAR2(50)  NOT NULL,
	"MEMBER_PW"       VARCHAR2(100) NOT NULL,
	"MEMBER_NICKNAME" NVARCHAR2(10) NOT NULL,
	"MEMBER_TEL"      CHAR(11)      NOT NULL,
	"MEMBER_ADDRESS"  NVARCHAR2(150),
	"PROFILE_IMG"     VARCHAR2(300),
	"ENROLL_DATE"			DATE DEFAULT CURRENT_DATE,
	"MEMBER_DEL_FL"		CHAR(1) DEFAULT 'N',
	"AUTHORITY_MEMBER"				NUMBER DEFAULT 1,
	
	CONSTRAINT "MEMBER_PK"         PRIMARY KEY("MEMBER_NO"),
	CONSTRAINT "MEMBER_DEL_FL_CHK" CHECK("MEMBER_DEL_FL" IN ('Y','N')),
	CONSTRAINT "AUTHORITY_MEMBER_CHK"     CHECK("AUTHORITY_MEMBER" IN ('1','2'))
);


-- COMMENT 추가
COMMENT ON COLUMN "MEMBER"."MEMBER_NO"       IS '회원번호(PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL"    IS '회원 아이디(ID)';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW"       IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원명';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL"      IS '회원 전화번호(-제외)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS"  IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG"     IS '프로필 이미지 경로';
COMMENT ON COLUMN "MEMBER"."ENROLL_DATE"     IS '가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL"    IS '탈퇴여부(Y,N)';
COMMENT ON COLUMN "MEMBER"."AUTHORITY_MEMBER" IS '회원권한(1:일반, 2:관리자)';



-- 회원 결제 클래스 테이블
CREATE TABLE "MEMBER_CLASS"(
	"MEMBER_NO"         NUMBER,
	"CLASS_CHARGE_DATE" DATE DEFAULT CURRENT_DATE,
	"CLASS_CODE"        NUMBER,
	
	CONSTRAINT "MEMBER_CLASS_PK"     PRIMARY KEY("MEMBER_NO")
);

COMMENT ON COLUMN "MEMBER_CLASS"."MEMBER_NO"       		IS '결제한 회원번호(PK)';
COMMENT ON COLUMN "MEMBER_CLASS"."CLASS_CHARGE_DATE"    IS '결제한 날짜';
COMMENT ON COLUMN "MEMBER_CLASS"."CLASS_CODE"       	IS '결제한 수업번호';

-- 회원번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;


/* 강사(TRAINNER) 테이블 생성*/
CREATE TABLE "TRAINNER"(
	"TRAINNER_NO"           NUMBER,
	"TRAINNER_EMAIL"        VARCHAR2(50)  NOT NULL,
	"TRAINNER_PW"           VARCHAR2(100) NOT NULL,
	"TRAINNER_NICKNAME"     NVARCHAR2(10) NOT NULL,
	"TRAINNER_TEL"          CHAR(11)      NOT NULL,
	"TRAINNER_ADDRESS"      NVARCHAR2(150),
	"PROFILE_IMG"    		VARCHAR2(300),
	"QUALIFICATION"         VARCHAR2(500),
	"ENROLL_DATE"			DATE DEFAULT CURRENT_DATE,
	"TRAINNER_DEL_FL"		CHAR(1) DEFAULT 'N',
	"AUTHORITY_TRAINNER"	NUMBER DEFAULT 1,
	
	CONSTRAINT "TRAINNER_PK"         		PRIMARY KEY("TRAINNER_NO"),
	CONSTRAINT "TRAINNER_DEL_FL_CHK"        CHECK("TRAINNER_DEL_FL" IN ('Y','N')),
	CONSTRAINT "AUTHORITY_TRAINNER_CHK"     CHECK("AUTHORITY_TRAINNER" IN ('1','2'))
);


-- COMMENT 추가
COMMENT ON COLUMN "TRAINNER"."TRAINNER_NO"        IS '강사번호(PK)';
COMMENT ON COLUMN "TRAINNER"."TRAINNER_EMAIL"     IS '강사 아이디(ID)';
COMMENT ON COLUMN "TRAINNER"."TRAINNER_PW"        IS '강사 비밀번호';
COMMENT ON COLUMN "TRAINNER"."TRAINNER_NICKNAME"  IS '강사명';
COMMENT ON COLUMN "TRAINNER"."TRAINNER_TEL"       IS '강사 전화번호(-제외)';
COMMENT ON COLUMN "TRAINNER"."TRAINNER_ADDRESS"   IS '강사 주소';
COMMENT ON COLUMN "TRAINNER"."PROFILE_IMG"        IS '프로필 이미지 경로';
COMMENT ON COLUMN "TRAINNER"."QUALIFICATION"      IS '강사 자격정보';
COMMENT ON COLUMN "TRAINNER"."ENROLL_DATE"        IS '가입일';
COMMENT ON COLUMN "TRAINNER"."TRAINNER_DEL_FL"    IS '탈퇴여부(Y,N)';
COMMENT ON COLUMN "TRAINNER"."AUTHORITY_TRAINNER" IS '권한(1:강사, 2:관리자)';


/* 관리자(MANAGER) 테이블 생성*/
CREATE TABLE "MANAGER"(
	"MANAGER_NO"         NUMBER,
	"MANAGER_EMAIL"      VARCHAR2(50)  NOT NULL,
	"MANAGER_PW"         VARCHAR2(100) NOT NULL,
	"MANAGER_NICKNAME"   NVARCHAR2(10) NOT NULL,
	"MANAGER_TEL"        CHAR(11)      NOT NULL,
	"MANAGER_ADDRESS"    NVARCHAR2(150),
	"PROFILE_IMG"    	 VARCHAR2(300),
	"ENROLL_DATE"		 DATE DEFAULT CURRENT_DATE,
	"MANAGER_DEL_FL"	 CHAR(1) DEFAULT 'N',
	"AUTHORITY_MANAGER"	 NUMBER DEFAULT 1,
	"AUTHORITY_MEMBER"	 NUMBER DEFAULT 2,
	"AUTHORITY_TRAINNER" NUMBER DEFAULT 2,
	
	CONSTRAINT "MANAGER_PK"         				  PRIMARY KEY("MANAGER_NO"),
	CONSTRAINT "MANAGER_DEL_FL_CHK" 				  CHECK("MANAGER_DEL_FL" IN ('Y','N')),
<<<<<<< HEAD
	CONSTRAINT "AUTHORITY_MANAGER"               CHECK("AUTHORITY_MANAGER" IN ('1','2')),
	CONSTRAINT "AUTHORITY_TRAINNER"               CHECK("AUTHORITY_TRAINNER" IN ('1','2')),
	CONSTRAINT "AUTHORITY_MEMBER"                 CHECK("AUTHORITY_MEMBER" IN ('1','2'))
=======
	CONSTRAINT "AUTHORITY_MANAGER_CHK"               CHECK("AUTHORITY_MANAGER" IN ('1','2'))
	CONSTRAINT "AUTHORITY_TRAINNER_CHK"               CHECK("AUTHORITY_TRAINNER" IN ('1','2'))
	CONSTRAINT "AUTHORITY_MEMBER_CHK"                 CHECK("AUTHORITY_MEMBER" IN ('1','2'))
>>>>>>> 19d0c1594787ea753adf44847aa40c541ff828b4
);


-- COMMENT 추가
COMMENT ON COLUMN "MANAGER"."MANAGER_NO"         IS '관리자 번호(PK)';
COMMENT ON COLUMN "MANAGER"."MANAGER_EMAIL"      IS '관리자 아이디(ID)';
COMMENT ON COLUMN "MANAGER"."MANAGER_PW"         IS '관리자 비밀번호';
COMMENT ON COLUMN "MANAGER"."MANAGER_NICKNAME"   IS '관리자명';
COMMENT ON COLUMN "MANAGER"."MANAGER_TEL"        IS '관리자 전화번호(-제외)';
COMMENT ON COLUMN "MANAGER"."MANAGER_ADDRESS"    IS '관리자 주소';
COMMENT ON COLUMN "MANAGER"."PROFILE_IMG"        IS '프로필 이미지 경로';
COMMENT ON COLUMN "MANAGER"."ENROLL_DATE"        IS '가입일';
COMMENT ON COLUMN "MANAGER"."MANAGER_DEL_FL"     IS '탈퇴여부(Y,N)';
COMMENT ON COLUMN "MANAGER"."AUTHORITY_MANAGER"  IS '관리자권한';
COMMENT ON COLUMN "MANAGER"."AUTHORITY_MEMBER"   IS '회원권한';
COMMENT ON COLUMN "MANAGER"."AUTHORITY_TRAINNER" IS '강사권한';


