/* 회원(MEMBER) 테이블 생성*/
CREATE TABLE "PROJECT"(
	"MEMBER_NO"       NUMBER,
	"MEMBER_EMAIL"       VARCHAR2(50)  NOT NULL,
	"MEMBER_PW"       VARCHAR2(100) NOT NULL,
	"MEMBER_NICKNAME" NVARCHAR2(10) NOT NULL,
	"MEMBER_TEL"      CHAR(11)      NOT NULL,
	"MEMBER_ADDRESS"  NVARCHAR2(150),
	"PROFILE_IMG"     VARCHAR2(300),
	"ENROLL_DATE"			DATE DEFAULT CURRENT_DATE,
	"MEMBER_DEL_FL"		CHAR(1) DEFAULT 'N',
	"AUTHORITY"				NUMBER DEFAULT 1,
	
	CONSTRAINT "MEMBER_PK"         PRIMARY KEY("MEMBER_NO"),
	CONSTRAINT "MEMBER_DEL_FL_CHK" CHECK("MEMBER_DEL_FL" IN ('Y','N')),
	CONSTRAINT "AUTHORITY_CHK"     CHECK("AUTHORITY" IN ('1','2'))
);


-- COMMENT 추가
COMMENT ON COLUMN "PROJECT"."MEMBER_NO"       IS '회원번호(PK)';
COMMENT ON COLUMN "PROJECT"."MEMBER_EMAIL"    IS '회원 아이디(ID)';
COMMENT ON COLUMN "PROJECT"."MEMBER_PW"       IS '회원 비밀번호';
COMMENT ON COLUMN "PROJECT"."MEMBER_NICKNAME" IS '회원명';
COMMENT ON COLUMN "PROJECT"."MEMBER_TEL"      IS '회원 전화번호(-제외)';
COMMENT ON COLUMN "PROJECT"."MEMBER_ADDRESS"  IS '회원 주소';
COMMENT ON COLUMN "PROJECT"."PROFILE_IMG"     IS '프로필 이미지 경로';
COMMENT ON COLUMN "PROJECT"."ENROLL_DATE"     IS '가입일';

COMMENT ON COLUMN "PROJECT"."MEMBER_DEL_FL"   IS '탈퇴여부(Y,N)';
COMMENT ON COLUMN "PROJECT"."AUTHORITY"       IS '권한(1:일반, 2:관리자)';



-- 회원번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;


-- 샘플 회원 데이터 삽입
INSERT INTO "PROJECT"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'member01@kh.or.kr', 'pass01!',
	  '샘플1', '01012341234', NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

SELECT *
FROM PROJECT;